services:
  - type: web
    name: twitch-collab
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: twitch-collab-db
          property: connectionString
      - key: PORT
        value: 10000
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: API_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://stirring-longma-bc41fd.netlify.app
      - key: WS_URL
        sync: false

databases:
  - name: twitch-collab-db
    plan: free
    ipAllowList: []
